<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>Comic Collector Live</title>
	<meta name="description" content="Comic Collector Live app for Android phone &amp; tablet
            and other Android devices  The Challenger">

    <!-- Font Awesome if you need it
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css">
	-->
        <link rel="stylesheet" href="https://unpkg.com/tailwindcss@2.2.19/dist/tailwind.min.css"/>
	<!--Replace with your tailwind.css once created-->

	<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,700" rel="stylesheet">

	<link rel="apple-touch-icon" sizes="57x57" href="https://cdn.andro.io/static/favicons/apple-icon-57x57.png">
	<link rel="apple-touch-icon" sizes="60x60" href="https://cdn.andro.io/static/favicons/apple-icon-60x60.png">
	<link rel="apple-touch-icon" sizes="72x72" href="https://cdn.andro.io/static/favicons/apple-icon-72x72.png">
	<link rel="apple-touch-icon" sizes="76x76" href="https://cdn.andro.io/static/favicons/apple-icon-76x76.png">
	<link rel="apple-touch-icon" sizes="114x114" href="https://cdn.andro.io/static/favicons/apple-icon-114x114.png">
	<link rel="apple-touch-icon" sizes="120x120" href="https://cdn.andro.io/static/favicons/apple-icon-120x120.png">
	<link rel="apple-touch-icon" sizes="144x144" href="https://cdn.andro.io/static/favicons/apple-icon-144x144.png">
	<link rel="apple-touch-icon" sizes="152x152" href="https://cdn.andro.io/static/favicons/apple-icon-152x152.png">
	<link rel="apple-touch-icon" sizes="180x180" href="https://cdn.andro.io/static/favicons/apple-icon-180x180.png">
	<link rel="icon" type="image/png" sizes="192x192"  href="https://cdn.andro.io/static/favicons/android-icon-192x192.png">
	<link rel="icon" type="image/png" sizes="32x32" href="https://cdn.andro.io/static/favicons/favicon-32x32.png">
	<link rel="icon" type="image/png" sizes="96x96" href="https://cdn.andro.io/static/favicons/favicon-96x96.png">
	<link rel="icon" type="image/png" sizes="16x16" href="https://cdn.andro.io/static/favicons/favicon-16x16.png">
	<link rel="manifest" href="https://cdn.andro.io/static/favicons/manifest.json">
	<meta name="msapplication-TileColor" content="#ffffff">
	<meta name="msapplication-TileImage" content="https://cdn.andro.io/static/favicons/ms-icon-144x144.png">


	<!-- Animation CSS-->
	<style>
		 /* ----------------------------------------------
		 * Generated by Animista
		 * w: http://animista.net, t: @cssanimista
		 * ---------------------------------------------- */

		.slide-in-bottom{-webkit-animation:slide-in-bottom .5s cubic-bezier(.25,.46,.45,.94) both;animation:slide-in-bottom .5s cubic-bezier(.25,.46,.45,.94) both}
		.slide-in-bottom-h1{-webkit-animation:slide-in-bottom .5s cubic-bezier(.25,.46,.45,.94) .5s both;animation:slide-in-bottom .5s cubic-bezier(.25,.46,.45,.94) .5s both}
		.slide-in-bottom-subtitle{-webkit-animation:slide-in-bottom .5s cubic-bezier(.25,.46,.45,.94) .75s both;animation:slide-in-bottom .5s cubic-bezier(.25,.46,.45,.94) .75s both}
		.fade-in{-webkit-animation:fade-in 1.2s cubic-bezier(.39,.575,.565,1.000) 1s both;animation:fade-in 1.2s cubic-bezier(.39,.575,.565,1.000) 1s both}
		.bounce-top-icons{-webkit-animation:bounce-top .9s 1s both;animation:bounce-top .9s 1s both}

		@-webkit-keyframes slide-in-bottom{0%{-webkit-transform:translateY(1000px);transform:translateY(1000px);opacity:0}100%{-webkit-transform:translateY(0);transform:translateY(0);opacity:1}}@keyframes  slide-in-bottom{0%{-webkit-transform:translateY(1000px);transform:translateY(1000px);opacity:0}100%{-webkit-transform:translateY(0);transform:translateY(0);opacity:1}}
		@-webkit-keyframes bounce-top{0%{-webkit-transform:translateY(-45px);transform:translateY(-45px);-webkit-animation-timing-function:ease-in;animation-timing-function:ease-in;opacity:1}24%{opacity:1}40%{-webkit-transform:translateY(-24px);transform:translateY(-24px);-webkit-animation-timing-function:ease-in;animation-timing-function:ease-in}65%{-webkit-transform:translateY(-12px);transform:translateY(-12px);-webkit-animation-timing-function:ease-in;animation-timing-function:ease-in}82%{-webkit-transform:translateY(-6px);transform:translateY(-6px);-webkit-animation-timing-function:ease-in;animation-timing-function:ease-in}93%{-webkit-transform:translateY(-4px);transform:translateY(-4px);-webkit-animation-timing-function:ease-in;animation-timing-function:ease-in}25%,55%,75%,87%{-webkit-transform:translateY(0);transform:translateY(0);-webkit-animation-timing-function:ease-out;animation-timing-function:ease-out}100%{-webkit-transform:translateY(0);transform:translateY(0);-webkit-animation-timing-function:ease-out;animation-timing-function:ease-out;opacity:1}}@keyframes  bounce-top{0%{-webkit-transform:translateY(-45px);transform:translateY(-45px);-webkit-animation-timing-function:ease-in;animation-timing-function:ease-in;opacity:1}24%{opacity:1}40%{-webkit-transform:translateY(-24px);transform:translateY(-24px);-webkit-animation-timing-function:ease-in;animation-timing-function:ease-in}65%{-webkit-transform:translateY(-12px);transform:translateY(-12px);-webkit-animation-timing-function:ease-in;animation-timing-function:ease-in}82%{-webkit-transform:translateY(-6px);transform:translateY(-6px);-webkit-animation-timing-function:ease-in;animation-timing-function:ease-in}93%{-webkit-transform:translateY(-4px);transform:translateY(-4px);-webkit-animation-timing-function:ease-in;animation-timing-function:ease-in}25%,55%,75%,87%{-webkit-transform:translateY(0);transform:translateY(0);-webkit-animation-timing-function:ease-out;animation-timing-function:ease-out}100%{-webkit-transform:translateY(0);transform:translateY(0);-webkit-animation-timing-function:ease-out;animation-timing-function:ease-out;opacity:1}}
		@-webkit-keyframes fade-in{0%{opacity:0}100%{opacity:1}}@keyframes  fade-in{0%{opacity:0}100%{opacity:1}}


	</style>

	<link rel="stylesheet" href="https://unpkg.com/flowbite@1.5.1/dist/flowbite.min.css" />



</head>

<body class="leading-normal tracking-normal text-gray-900" style="font-family: 'Source Sans Pro', sans-serif;">

<style>
	.no-spinners {
		-moz-appearance: textfield;
	}

	.no-spinners::-webkit-outer-spin-button,
	.no-spinners::-webkit-inner-spin-button {
		margin: 0;
		-webkit-appearance: none;
	}
</style>


<div class="h-screen pb-14 bg-right bg-cover" >
	<!--Nav-->
	<div class="w-full container mx-auto p-6">

		<div class="w-full flex items-center justify-between">
			<a class="flex items-center text-indigo-400 no-underline hover:no-underline font-bold text-2xl lg:text-4xl"  href="#">
				 <img src="https://lh4.ggpht.com/LNfYSp5KhqCtlhHTnyZW92na7BTjLtVMOrd7B8N7scCyDuicbAAb5YxjdIrynTSh2-5U=w300" style="height: 35px !important; margin: 5px;" class="rounded"> Comic Collector Live
			</a>

		</div>
	</div>


	<section>


		<div class="relative max-w-screen-xl px-4 py-8 mx-auto">
			<div class="grid items-start grid-cols-1 gap-8 md:grid-cols-2">



				<div >


					<div id="animation-carousel" class="relative" data-carousel="static">
						<!-- Carousel wrapper -->
						<div class="overflow-hidden relative rounded-lg " style="height: 40rem">
							<!-- Item 1 -->
							<div class="duration-700 ease-in-out absolute inset-0 transition-all transform translate-x-0 z-20" data-carousel-item="">
								<img
										alt="Android application Comic Collector Live screenshort"

										src="https://lh5.ggpht.com/oBK1PQ9BMWH6ROzP2KTJz1dFWh6qLa32SFffR_Yg3FdgM0MPumqBsIX8-BHCXupCNN8G=w3840"
								/>

							</div>

						
							<!-- Item 2 -->
							<div class="duration-700 ease-in-out absolute inset-0 transition-all transform translate-x-full z-10" data-carousel-item="">
								<img 	src="https://lh4.ggpht.com/I0ELf8QHuquMPrr3PL6EWowF1nPdwuknMuAp6ZXhvMQNXmiVOLWHBtsxqh8ReVsBeu8=w3840"
										 alt="...">
							</div>
						
													<!-- Item 3 -->
							<div class="duration-700 ease-in-out absolute inset-0 transition-all transform -translate-x-full z-10" data-carousel-item="">
								<img src="https://lh5.ggpht.com/oBK1PQ9BMWH6ROzP2KTJz1dFWh6qLa32SFffR_Yg3FdgM0MPumqBsIX8-BHCXupCNN8G=h900"

									 alt="...">
							</div>
							
						</div>
						<!-- Slider indicators -->
						<div class="flex absolute bottom-5 left-1/2 z-30 space-x-3 -translate-x-1/2">
							<button type="button" class="w-3 h-3 rounded-full bg-white dark:bg-gray-800" aria-current="true" aria-label="Slide 1" data-carousel-slide-to="0"></button>
							<button type="button" class="w-3 h-3 rounded-full bg-white/50 dark:bg-gray-800/50 hover:bg-white dark:hover:bg-gray-800" aria-current="false" aria-label="Slide 2" data-carousel-slide-to="1"></button>
							<button type="button" class="w-3 h-3 rounded-full bg-white/50 dark:bg-gray-800/50 hover:bg-white dark:hover:bg-gray-800" aria-current="false" aria-label="Slide 3" data-carousel-slide-to="2"></button>
						</div>
						<!-- Slider controls -->
						<button type="button" class="flex absolute top-0 left-0 z-30 justify-center items-center px-4 h-full cursor-pointer group focus:outline-none" data-carousel-prev="">
        <span class="inline-flex justify-center items-center w-8 h-8 rounded-full sm:w-10 sm:h-10 bg-white/30 dark:bg-gray-800/30 group-hover:bg-white/50 dark:group-hover:bg-gray-800/60 group-focus:ring-4 group-focus:ring-white dark:group-focus:ring-gray-800/70 group-focus:outline-none">
            <svg aria-hidden="true" class="w-5 h-5 text-white sm:w-6 sm:h-6 dark:text-gray-800" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7"></path></svg>
            <span class="sr-only">Previous</span>
        </span>
						</button>
						<button type="button" class="flex absolute top-0 right-0 z-30 justify-center items-center px-4 h-full cursor-pointer group focus:outline-none" data-carousel-next="">
        <span class="inline-flex justify-center items-center w-8 h-8 rounded-full sm:w-10 sm:h-10 bg-white/30 dark:bg-gray-800/30 group-hover:bg-white/50 dark:group-hover:bg-gray-800/60 group-focus:ring-4 group-focus:ring-white dark:group-focus:ring-gray-800/70 group-focus:outline-none">
            <svg aria-hidden="true" class="w-5 h-5 text-white sm:w-6 sm:h-6 dark:text-gray-800" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"></path></svg>
            <span class="sr-only">Next</span>
        </span>
						</button>
					</div>




				</div>
				<div class="sticky top-0">



					<div class="flex justify-between mt-8">
						<div class="max-w-[35ch]">
							<h1 class="text-2xl font-bold">
								Comic Collector Live
							</h1>

															<p class="mt-0.5 text-sm">
									by The Challenger
								</p>
							

							

							

						</div>

						<p class="text-lg font-bold">
						<div itemprop="offers" itemscope itemtype="https://schema.org/Offer">
							<span itemprop="price"
								  class="border border-blue-700 rounded-full tracking-wide px-6 font-medium py-2 text-xl bg-gray-100 text-black-600"
							>
                            									free
								                        </span>
							<meta itemprop="priceCurrency" content="USD" />
						</div>
						</p>
					</div>
<br>
					<div>
													<span class="border border-red-700 rounded-full tracking-wide px-4 font-medium py-2 text-xl bg-gray-100 text-black-600"
							>
								not available
							</span>
							<br><br>

							<br>
															<br>
								<a href="https://andro.io/cat-5-comics" target="_blank"><strong class="border border-blue-600 rounded-full tracking-wide px-3 font-medium py-0.5 text-xs bg-gray-100 text-blue-600">
										Find similar to Comic Collector Live : Comics
									</strong>
								</a>
																		</div>

<br>
					<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
					<ins class="adsbygoogle"
						 style="display:block"
						 data-ad-client="ca-pub-3746326561778403"
						 data-ad-slot="5915702172"
						 data-ad-format="auto"></ins>
					<script>
						(adsbygoogle = window.adsbygoogle || []).push({});
					</script>

					<details class="relative mt-4 group">
						<summary class="block">
							<div>

															
							This application is a companion application for collectors and fans who subscribe to ComicCollectorLive.comEasily search through our library of virtually every comic book ever published. Check out new releases, create a wish list, and get the latest reviews on comic books both new and old. Scroll through cover art, zoom and create wall paper from comic book covers. Review current selling trends and prices from more than 150 comic shops.<br />
ComicCollectorLive.com is fast becoming the one stop shop for thousands of collectors and fans. Now, experience everything comics with this exciting and easy to use comic collecting companion! <br />
The Best Comic Book Library In Any Universe - Research virtually every comic book in existence. Includes full covers, biographical information, and more. Get competitive market pricing from hundreds of comic shops and private collectors nation wide.<br />
Browse Covers – Having a hard time keeping up with all the variant covers? Easily thumb through every cover and variant from golden age to modern. Easily set your favorite cover as your wall paper.<br />
New Releases - What just came out today? This week? Last week? Next week? It's all here right at your fingertips. New and upcoming issues are added every day!<br />
Reviews - What are they saying about that new series? Do people like it? Now, instantly you can know. <br />
Wish List Management - Add items to your wish list. Review your wish list right in the palm of your hand.<br />
Enhance Your LCS Experience<br />
This app will change your trip to your Local Comic Shop forever.<br />
Question: "Is that book on the wall a 1:10 or a 1:25 variant?"Question: "Did Deadpool #900 come out this week or last...?"<br />
Question: "Excuse me, sir...I'm looking for (holds up Android with an image of Transformers Devastation #2 Sketch Cover) THIS book?"<br />
Question: "Do I need this zombie cover or this zombie cover? I think I better check my wish list, eh?"<br />
Question: "I heard that issue of Batman wasn't all that. Wonder what reviewers say about that book on CCL?"<br />
Don't be without this app when you go to the shop. It is like having a comic book encyclopedia right in the palm of your hand.<br />
Integrates Seamlessly With Your Existing Comic Collector Live Account. If you are not already a ComicCollectorLive.com member… you should be. The CCL Android app will integrate with your existing account using your same login and password. When you update your wish list on Android it will update your web account and your desktop software as well. The Android app is designed to enhance your existing CCL paid membership.<br />
REQUIREMENTS:An Active ComicCollectorLive.com Account<br />
Find Us:<br />
Web: www.ComicCollectorLive.comTwitter: @ComicBlaze
						

					</details>

				</div>
			</div>
		</div>

	</section>


		<footer class="text-center">
		<div class="max-w-screen-xl px-4 py-12 mx-auto sm:px-6 lg:px-8">
			<div class="max-w-3xl mx-auto space-y-6">
				<div class="flex justify-center space-x-6">
					<a class="text-blue-500 hover:text-opacity-75" href="https://twitter.com/andro_io" target="_blank" rel="noreferrer">
						<span class="sr-only"> Twitter </span>

						<svg class="w-8 h-8" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
							<path d="M8.29 20.251c7.547 0 11.675-6.253 11.675-11.675 0-.178 0-.355-.012-.53A8.348 8.348 0 0022 5.92a8.19 8.19 0 01-2.357.646 4.118 4.118 0 001.804-2.27 8.224 8.224 0 01-2.605.996 4.107 4.107 0 00-6.993 3.743 11.65 11.65 0 01-8.457-4.287 4.106 4.106 0 001.27 5.477A4.072 4.072 0 012.8 9.713v.052a4.105 4.105 0 003.292 4.022 4.095 4.095 0 01-1.853.07 4.108 4.108 0 003.834 2.85A8.233 8.233 0 012 18.407a11.616 11.616 0 006.29 1.84" />
						</svg>
					</a>

				</div>


				
				<nav class="grid grid-cols-2 gap-4 p-6 text-sm font-medium bg-gray-100 rounded-lg sm:grid-cols-3 lg:grid-cols-6">
					<a class="hover:opacity-75" href="https://andro.io/genres"> App categories </a>
					<a class="hover:opacity-75" href="https://andro.io/sitemap.html"> Sitemap </a>
					<a class="hover:opacity-75" href="https://top-apps.andro.io/"> Top games and apps </a>
					<a class="hover:opacity-75" href="https://andro.io/contacts"> Support </a>
					<a class="hover:opacity-75" href="https://andro.io/eula"> EULA </a>
					<a class="hover:opacity-75" href="https://andro.io/privacy"> Privacy policy </a>
				</nav>

				<p class="max-w-lg mx-auto text-xs text-gray-500">
					Andro.io - Free Android application websites service <br>
					Contact us: <a href="/cdn-cgi/l/email-protection#7f161119103f1e0f0f0c0b100d511610"><span class="__cf_email__" data-cfemail="40292e262f0021303033342f326e292f">[email&#160;protected]</span></a> Abuse: <a href="/cdn-cgi/l/email-protection#d9b8bbacaabc99b8a9a9aaadb6abf7b0b6"><span class="__cf_email__" data-cfemail="eb8a899e988eab8a9b9b989f8499c58284">[email&#160;protected]</span></a>
				</p>

				<p class="text-xs font-medium">
					&copy; 2022 AndroIo
				</p>
			</div>
		</div>
	</footer>

</div>


<script data-cfasync="false" src="/cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"></script><script>
	(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
		(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
			m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

	ga('create', 'UA-2422930-59', 'auto');
	ga('send', 'pageview');

</script>

  <!-- jQuery if you need it
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  -->



<script src="https://unpkg.com/flowbite@1.5.1/dist/flowbite.js"></script>



</body>
</html>